
package View;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel4 = new javax.swing.JPanel();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        SidePanel = new javax.swing.JPanel();
        IconJlabel = new javax.swing.JLabel();
        AdminJlabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        Side2Jpanel = new javax.swing.JPanel();
        DashboardPane = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        RegisterJbutton = new javax.swing.JButton();
        OpportunityJbutton = new javax.swing.JButton();
        InboxJbutton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        UserNameJlaber = new javax.swing.JLabel();
        EmailJlabel = new javax.swing.JLabel();
        ContactJlabel = new javax.swing.JLabel();
        LocationJlabel = new javax.swing.JLabel();
        UserNameJfield = new javax.swing.JTextField();
        EmailJfield = new javax.swing.JTextField();
        ContactJfield = new javax.swing.JTextField();
        LocationJfield = new javax.swing.JTextField();
        UpdateJbutton = new javax.swing.JButton();
        AddJbutton = new javax.swing.JButton();
        ClearJbutton = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        RegisterUserJtable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        OpportunityJtable = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserJtable = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SidePanel.setBackground(new java.awt.Color(102, 102, 102));
        SidePanel.setForeground(new java.awt.Color(255, 255, 255));
        SidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconJlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/admin profile.png"))); // NOI18N
        IconJlabel.setText("jLabel1");
        SidePanel.add(IconJlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 25, 55, -1));

        AdminJlabel.setText("Admin");
        SidePanel.add(AdminJlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 81, 36, -1));
        SidePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 103, 194, 10));
        SidePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 251, -1, -1));

        DashboardPane.setBackground(new java.awt.Color(113, 113, 116));

        RegisterJbutton.setBackground(new java.awt.Color(223, 194, 194));
        RegisterJbutton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        RegisterJbutton.setForeground(new java.awt.Color(153, 0, 51));
        RegisterJbutton.setText("Registered users: 56");
        RegisterJbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RegisterJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterJbuttonActionPerformed(evt);
            }
        });

        OpportunityJbutton.setBackground(new java.awt.Color(193, 193, 220));
        OpportunityJbutton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        OpportunityJbutton.setForeground(new java.awt.Color(102, 0, 102));
        OpportunityJbutton.setText("Opportunities: 56");
        OpportunityJbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OpportunityJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpportunityJbuttonActionPerformed(evt);
            }
        });

        InboxJbutton.setBackground(new java.awt.Color(211, 235, 219));
        InboxJbutton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        InboxJbutton.setForeground(new java.awt.Color(0, 51, 51));
        InboxJbutton.setText("Inbox: 5");
        InboxJbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        InboxJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InboxJbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegisterJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpportunityJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InboxJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(460, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(RegisterJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(OpportunityJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(InboxJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(410, Short.MAX_VALUE))
        );

        DashboardPane.addTab("Dashboard", jPanel8);

        UserNameJlaber.setText("User Name");

        EmailJlabel.setText("Email");

        ContactJlabel.setText("Contact number");

        LocationJlabel.setText("Location");

        UserNameJfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameJfieldActionPerformed(evt);
            }
        });

        ContactJfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactJfieldActionPerformed(evt);
            }
        });

        LocationJfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationJfieldActionPerformed(evt);
            }
        });

        UpdateJbutton.setBackground(new java.awt.Color(180, 218, 239));
        UpdateJbutton.setText("Update");
        UpdateJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateJbuttonActionPerformed(evt);
            }
        });

        AddJbutton.setBackground(new java.awt.Color(167, 202, 167));
        AddJbutton.setText("Add");
        AddJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddJbuttonActionPerformed(evt);
            }
        });

        ClearJbutton.setBackground(new java.awt.Color(195, 13, 13));
        ClearJbutton.setText("Clear");
        ClearJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearJbuttonActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(233, 233, 198));
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        RegisterUserJtable.setBackground(new java.awt.Color(181, 174, 210));
        RegisterUserJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User Name", "Email", "Contact Number", "Location"
            }
        ));
        jScrollPane4.setViewportView(RegisterUserJtable);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(LocationJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LocationJfield))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(ContactJlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ContactJfield))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserNameJlaber)
                            .addComponent(EmailJlabel))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailJfield, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserNameJfield, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(AddJbutton)
                .addGap(45, 45, 45)
                .addComponent(UpdateJbutton)
                .addGap(71, 71, 71)
                .addComponent(ClearJbutton)
                .addGap(83, 83, 83)
                .addComponent(btndelete))
            .addComponent(jScrollPane4)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserNameJlaber)
                    .addComponent(UserNameJfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailJlabel)
                    .addComponent(EmailJfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactJlabel)
                    .addComponent(ContactJfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocationJlabel)
                    .addComponent(LocationJfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddJbutton)
                    .addComponent(UpdateJbutton)
                    .addComponent(ClearJbutton)
                    .addComponent(btndelete))
                .addContainerGap(256, Short.MAX_VALUE))
        );

        DashboardPane.addTab("Registered User", jPanel9);

        OpportunityJtable.setBackground(new java.awt.Color(0, 51, 102));
        OpportunityJtable.setForeground(new java.awt.Color(204, 204, 204));
        OpportunityJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Vietnam", "Tisa Lama", "11255", "Kathmandu", "tisalama@gmail.com"},
                {"2", "Egypt", "Shreya Kc", "33456", "Bhaktapur", "Kcshreya@gmail.com"},
                {"3", null, "Hina Maka", "787845", "Patan", "makahina@gmail.com"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Opp_ID", "Opportunity", "Name", "Contact Number", "Location", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(OpportunityJtable);

        DashboardPane.addTab("Opportunities applied", jScrollPane3);

        UserJtable.setBackground(new java.awt.Color(50, 58, 58));
        UserJtable.setForeground(new java.awt.Color(204, 204, 204));
        UserJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Tisa lama", "lamatisa@gmail.com", "How to apply for vietnam?"},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Email", "Message"
            }
        ));
        jScrollPane1.setViewportView(UserJtable);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );

        DashboardPane.addTab("User Messages", jPanel10);

        javax.swing.GroupLayout Side2JpanelLayout = new javax.swing.GroupLayout(Side2Jpanel);
        Side2Jpanel.setLayout(Side2JpanelLayout);
        Side2JpanelLayout.setHorizontalGroup(
            Side2JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Side2JpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DashboardPane)
                .addContainerGap())
        );
        Side2JpanelLayout.setVerticalGroup(
            Side2JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Side2JpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DashboardPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Side2Jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Side2Jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private String validateInput(String userName, String email, String contactNumber, String location) {
    // Validate user name
    if (userName.isEmpty()) {
        return "User  Name cannot be empty.";
    }

    // Validate email
    if (!email.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
        return "Please enter a valid email address.";
    }

    // Validate contact number
    if (contactNumber.length() != 10 || !contactNumber.matches("\\d+")) {
        return "Contact Number must be 10 digits.";
    }

    // Validate location
    if (location.isEmpty()) {
        return "Location cannot be empty.";
    }

    // If all validations pass
    return null; // No error
}
    

    private void RegisterJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterJbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterJbuttonActionPerformed

    private void OpportunityJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpportunityJbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpportunityJbuttonActionPerformed

    private void InboxJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InboxJbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InboxJbuttonActionPerformed

    private void UserNameJfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameJfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameJfieldActionPerformed

    private void LocationJfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationJfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationJfieldActionPerformed

    private void UpdateJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateJbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateJbuttonActionPerformed

    private void ClearJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearJbuttonActionPerformed

            // Clear the input fields
    UserNameJfield.setText("");
    EmailJfield.setText("");
    ContactJfield.setText("");
    LocationJfield.setText("");

        
    }//GEN-LAST:event_ClearJbuttonActionPerformed

    private void ContactJfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactJfieldActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_ContactJfieldActionPerformed

    private void AddJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddJbuttonActionPerformed
                                          
    // Get values from input fields
    String userName = UserNameJfield.getText().trim();
    String email = EmailJfield.getText().trim();
    String contactNumber = ContactJfield.getText().trim();
    String location = LocationJfield.getText().trim();

    // Validate input
    String validationError = validateInput(userName, email, contactNumber, location);
    if (validationError != null) {
        JOptionPane.showMessageDialog(this, validationError, "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Create a new row data array
    Object[] newRow = { userName, email, contactNumber, location };

    // Get the table model and add the new row
    DefaultTableModel model = (DefaultTableModel) RegisterUserJtable.getModel();
    model.addRow(newRow);

    // Clear the input fields after adding
    UserNameJfield.setText("");
    EmailJfield.setText("");
    ContactJfield.setText("");
    LocationJfield.setText("");
    }//GEN-LAST:event_AddJbuttonActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:                                         
    // Get the selected row index
    int selectedRow = RegisterUserJtable.getSelectedRow();
    
    // Check if a row is selected
    if (selectedRow != -1) {
        // Get the table model
        DefaultTableModel model = (DefaultTableModel) RegisterUserJtable.getModel();
        
        // Remove the selected row
        model.removeRow(selectedRow);
    } else {
        // Show a message if no row is selected
        JOptionPane.showMessageDialog(this, "Please select a user to delete.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddJbutton;
    private javax.swing.JLabel AdminJlabel;
    private javax.swing.JButton ClearJbutton;
    private javax.swing.JTextField ContactJfield;
    private javax.swing.JLabel ContactJlabel;
    private javax.swing.JTabbedPane DashboardPane;
    private javax.swing.JTextField EmailJfield;
    private javax.swing.JLabel EmailJlabel;
    private javax.swing.JLabel IconJlabel;
    private javax.swing.JButton InboxJbutton;
    private javax.swing.JTextField LocationJfield;
    private javax.swing.JLabel LocationJlabel;
    private javax.swing.JButton OpportunityJbutton;
    private javax.swing.JTable OpportunityJtable;
    private javax.swing.JButton RegisterJbutton;
    private javax.swing.JTable RegisterUserJtable;
    private javax.swing.JPanel Side2Jpanel;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JButton UpdateJbutton;
    private javax.swing.JTable UserJtable;
    private javax.swing.JTextField UserNameJfield;
    private javax.swing.JLabel UserNameJlaber;
    private javax.swing.JButton btndelete;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
